name: Release Management

on:
  release:
    types: [published]

jobs:
  release:
    name: Release to gem hosts
    runs-on: ubuntu-latest
    steps:
      - name: Setup ruby
        uses: actions/setup-ruby@v1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Setup credentials and versioning
        run: |
          gem install git-lite-version-bump keycutter roo
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:push_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          printf -- ":github_api_key: Bearer ${GPR_API_KEY}\n" >> $HOME/.gem/credentials
        env:
          RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
          GPR_API_KEY: ${{secrets.GITHUB_TOKEN}}
      - name: Build gem
        run: gem build ./mitre-inspec-objects.gemspec
      - name: Get gem version
        run: echo "::set-env name=VERSION::$(ls *.gem | grep -Po '(\d+.)+\d+')"
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true 
      - name: Publish to RubyGems
        run: |
          gem push -k push_api_key --host https://rubygems.org *.gem
      - name: Publish to GPR
        run: |
          gem push -k github_api_key --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          OWNER: mitre